employee_salary:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: postgres
      host: host.docker.internal
      pass: postgres
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
  target: dev